definitions:
  is-feature: &is-feature >-
    build.branch != "main"
    || build.pull_request.id != null

  is-release: &is-release >-
    build.branch == "main"
    && build.pull_request.id == null

  matrix: &matrix
    setup:
      php:
        - "8.1"
        - "8.2"
        - "8.3"
      composer:
        - "2"
        - "2.2"
        - "2.3"
        - "2.4"
        - "2.5"
        - "2.6"
        - "2.7"
        - "2.8"

  agents-amd64: &agents-amd64
    queue: docker-builders

  agents-arm64: &agents-arm64
    queue: docker-builders-arm

  docker-password: &docker-password
    seek-oss/aws-sm#v2.3.2:
      env:
        F1BUILDER_DOCKER_PASSWORD: forumone/docker-hub

  docker-login: &docker-login
    docker-login#v3.0.0:
      username: f1builder
      password-env: F1BUILDER_DOCKER_PASSWORD

steps:
  # Feature steps: build and discard images
  - group: ":docker: Feature builds (amd64)"
    steps:
      - label: "Build :php: {{matrix.php}} + :composer: {{matrix.composer}} (amd64)"
        matrix: *matrix
        agents: *agents-amd64
        if: *is-feature

        concurrency: 4
        concurrency_group: $BUILDKITE_PIPELINE_SLUG/amd64

        command: >-
          docker buildx build .
          --progress=plain
          --output=type=tar,dest=/dev/null
          --build-arg=PHP_VERSION={{matrix.php}}
          --build-arg=COMPOSER_VERSION={{matrix.composer}}

  - group: ":docker: Feature builds (arm64)"
    steps:
      - label: "Build :php: {{matrix.php}} + :composer: {{matrix.composer}} (arm64)"
        matrix: *matrix
        agents: *agents-arm64
        if: *is-feature

        concurrency: 4
        concurrency_group: $BUILDKITE_PIPELINE_SLUG/arm64

        command: >-
          docker buildx build .
          --progress=plain
          --output=type=tar,dest=/dev/null
          --build-arg=PHP_VERSION={{matrix.php}}
          --build-arg=COMPOSER_VERSION={{matrix.composer}}

  # Production steps: build and push images, then manually create multi-arch manifests
  - group: ":docker: Build and push (amd64)"
    steps:
      - label: "Build and push :php: {{matrix.php}} + :composer: {{matrix.composer}} (amd64)"
        matrix: *matrix
        agents: *agents-amd64
        if: *is-release

        concurrency: 4
        concurrency_group: $BUILDKITE_PIPELINE_SLUG/amd64

        plugins: [*docker-password, *docker-login]
        commands:
          - >-
            docker buildx build .
            --progress=plain
            --output=type=docker
            --build-arg=PHP_VERSION={{matrix.php}}
            --build-arg=COMPOSER_VERSION={{matrix.composer}}
            --tag=forumone/composer:{{matrix.composer}}-php-{{matrix.php}}-amd64
          - docker push forumone/composer:{{matrix.composer}}-php-{{matrix.php}}-amd64

  - group: ":docker: Build and push (arm64)"
    steps:
      - label: "Build and push :php: {{matrix.php}} + :composer: {{matrix.composer}} (arm64)"
        matrix: *matrix
        agents: *agents-arm64
        if: *is-release

        concurrency: 4
        concurrency_group: $BUILDKITE_PIPELINE_SLUG/arm64

        plugins: [*docker-password, *docker-login]
        commands:
          - >-
            docker buildx build .
            --progress=plain
            --output=type=docker
            --build-arg=PHP_VERSION={{matrix.php}}
            --build-arg=COMPOSER_VERSION={{matrix.composer}}
            --tag=forumone/composer:{{matrix.composer}}-php-{{matrix.php}}-arm64
          - docker push forumone/composer:{{matrix.composer}}-php-{{matrix.php}}-arm64

  - wait: ~

  - group: ":docker: Assemble manifests"
    steps:
      - label: ":docker: Assemble :php: {{matrix.php}} + :composer: {{matrix.composer}}"
        matrix: *matrix
        if: *is-release

        concurrency: 4
        concurrency_group: $BUILDKITE_PIPELINE_SLUG/manifest

        plugins: [*docker-password, *docker-login]
        commands:
          - >-
            docker manifest create
            forumone/composer:{{matrix.composer}}-php-{{matrix.php}}
            forumone/composer:{{matrix.composer}}-php-{{matrix.php}}-amd64
            forumone/composer:{{matrix.composer}}-php-{{matrix.php}}-arm64
          - docker manifest push forumone/composer:{{matrix.composer}}-php-{{matrix.php}}
